#!/bin/sh
# This script is executed at boot time before VyOS configuration is applied.
# Any modifications required to work around unfixed bugs or use
# services not available through the VyOS CLI system can be placed here.

# Fix for containers requiring a custom user/group id
# and Vyos not preserving file perms on upgrade
#!/bin/sh
# This script is executed at boot time before VyOS configuration is applied.
# Any modifications required to work around unfixed bugs or use
# services not available through the VyOS CLI system can be placed here.

mkdir -p /tmp/bind/cache
sudo chown -R 104 /tmp/bind/cache
mkdir -p /tmp/onepassword/data
chown -R 999 /tmp/onepassword/data

# Mount USB backup drive
backupdest=/media/usb-backup
sudo mkdir -p "$backupdest"
sudo mount.exfat-fuse -o rw,uid=vyos,gid=vyattacfg /dev/disk/by-id/usb-USB_SanDisk_3.2Gen1_0501a7b57d3aebec39c1d5c2222ed068372d5e7cd6d2c74e4c775e5ee97edac01d4c000000000000000000008e80aa130084171083558107cc2c2c67-0:0-part1 "$backupdest"
