---
name: Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry-Run
        default: "false"
        required: false
      logLevel:
        description: Log-level
        default: debug
        required: false
  schedule:
    - cron: 0 * * * *
  push:
    branches: ["main"]
    paths:
      - .github/renovate.json5
      - .github/renovate/**.json5

env:
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_DRY_RUN: "${{ inputs.dryRun == true }}"
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_CONFIG_FILE: .github/renovate.json5
  LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Generate token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app-id: "${{ secrets.TROSVALD_APP_ID }}"
          private-key: "${{ secrets.TROSVALD_APP_PRIVATE_KEY }}"
      - name: Override default config from dispatch variables
        run: |
          echo "RENOVATE_DRY_RUN=${{ github.event.inputs.dryRun || env.RENOVATE_DRY_RUN }}" >> "${GITHUB_ENV}"
          echo "LOG_LEVEL=${{ github.event.inputs.logLevel || env.LOG_LEVEL }}" >> "${GITHUB_ENV}"
      - name: Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          configurationFile: "${{ env.RENOVATE_CONFIG_FILE }}"
          token: "${{ steps.generate-token.outputs.token }}"